### PR TITLE
Mainly typos and comma fixes

### PR DESCRIPTION
**Pull request by hasenbalg**
I found a view minor things here and there.

### CODE REVIEW

**Comment by sypets** [comment]
@hasenbalg This looks great! However, there are some conflicts. This is probably due to some changes I made recently. Your PR looks like it is based on an older version.

If you edit locally, it is best to start your PR from an up-to-date version. So if you cloned the repo from your GitHub workspace, you can add the upstream URL, _before_ you start a branch, you can do for example:

```
git remote add upstream https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid.git
git pull origin master
```

(If you just pull from "origin", you will not get the latest updates because "origin" is the forked repo on your local workspace)

This will make sure you got all updates from the main repo (in TYPO3-Documentation) and not your forked repo (which may no longer be up-to-date). 

For the conflicts in _this_ PR: Do you want to fix it? Otherwise, I can do it for you.

Apart from that, I glanced through some of your changes and they look very good! :thumbsup:

**Comment by sypets** [comment]
Sorry, I messed up. Should be:


```
git remote add upstream https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid.git
git pull upstream master
```

("upstream", not "origin")

**Comment by hasenbalg** [comment]
Hi, thank you for the guidence! I will fix it up in the next days. Have a nice day!On 15 May 2019 12:55, Sybille Peters <notifications@github.com> wrote:Sorry, I messed up. Should be:
git remote add upstream https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid.git
git pull upstream master

("upstream", not "origin")

**Comment by sypets** [comment]
I looked a little closer at your PR: You are trying to merge "hasenbalg:**latest"** into "TYPO3-Documentation:latest" and the last change before your changes is August 2, 2018. Usually, you should be merging a branch. Due to this, the changes GitHub shows for this PR are wrong (note the top commit from 2018, this PR is showing all the older commits except the last 4 (which are your latest 4 commits). 

github


This is no drama and can all be sorted out, but I will close this PR to avoid confusion. Nothing is lost. You can still use your commits to create a new branch and a new PR. 

But, not that the file "Backend Modules" has been completely reduced to a link to "TYPO3 Explained", so you can throw away your comit ["minor expression changes"](https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/263/commits/dce2d670f32ab268c8ce7b6259066d261c4014cd)

Hope that is ok with you. 

For the future I would suggest:

1. As already mentioned, make sure your local git repository [is up to date](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/LocalEditing.html#keep-your-local-fork-up-to-date) before you start.
2. See this resource: [for local editing](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/LocalEditing.html)
3. As an alternative, minor changes can also be made online directly, see https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html
4. If in doubt, keep the PR small.
5. If you need help, don't hesitate to ask in Slack channel **#typo3-documentation**. (see https://docs.typo3.org/typo3cms/HowToDocument/HowToGetHelp.html)

**Comment by sypets** [comment]
I created a new PR and merged your changes: #264

**Pull request closed without merging**
