### PR TITLE
[TASK] Content review

### PR DESCRIPTION
**Pull request by alexanderschnitzler**
This PR adds todo's to the documentation in case of wrong statements or statements that need to be improved.

### CODE REVIEW

**Comment by linawolf** [comment]
Are you still working on this @alexanderschnitzler ?

**Comment by alexanderschnitzler** [comment]
No, not at the moment. New job, very little time. But my comments so far are valid. We can review and merge if you like and I finish my review later this year.

**Comment by linawolf** [comment]
@alexanderschnitzler if you remove the draft I can merge it. If we don't get it merged we will have more and more conflicts

**Comment by susannemoog** [comment]
@linawolf if you have time to resolve the conflicts I'd say we merge the current state.

**Pull request merged**
