### PR TITLE
Add pluginNamespace option

### PR DESCRIPTION
**Pull request by pogosheep**
Add the option with short description.

It's implemented at `\TYPO3\CMS\Extbase\Service\ExtensionService->getPluginNamespace()`

### CODE REVIEW

**Comment by marble** [comment]
Thanks! I removed some typos, I think. I hope it's alright with you. http://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html#typoscript-configuration

**Comment by pogosheep** [comment]
Yes thanks ... I've missed one thing ... take a look at http://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html#typoscript-configuration with updated rendering. The order is wrong. We should add `pluginNamespace` after `templateRootPath`

**Comment by marble** [comment]
Oops, that was me, I changed that order. Because everything is sorted alphabetically there. Why would you change that?

**Comment by pogosheep** [comment]
Because the other options are all related. You configure where to look for specific files like templates.

The new option is related to other things like GET-Parameter and such. But if sorting is alphabetical it's okay to me, didn't notice the sorting.

**Pull request merged**
