### PR TITLE
change naming off TCA field for language parameter

### PR DESCRIPTION
**Pull request by mcmietz**
In paragraph before TCA code example fields "l10n_parent" "l10n_diffsource" are dicribed.
But in code example "l18n_parent" and "l18n_diffsource" is used. But this fields only used for tt_content table.
Changed naming of TCA fields to "l10n_parent" and "l10n_diffsource".

### CODE REVIEW

**Comment by susannemoog** [comment]
I'm never sure which one is technically more correct - can someone check with the original code in blog example? (this code should match the code there) From the word itself (localization) - l10n would be correct.

**Comment by mbrodala** [comment]
@susannemoog Exactly. That's why `l18n` does not make sense. This is a mix of `l10n` (`localization`) and `i18n` (`internationalization`).

So again: yes, `l10n_` must be used.

**Comment by mcmietz** [comment]
Ok, so the blog example really creates fields l18n_parent and l18n_diffsource in the database for table tx_blogexample_domain_model_blog. 
For person, again, l10n_ .

Should we rather smooth this out in the blog example and then adjust the doc accordingly?

**Comment by mbrodala** [comment]
Yes, this would make sense IMO. We should not keep broken examples around for historic reasons. It's bad enough that we have a popular example with `tt_content` which still does it wrong.

**Comment by linawolf** [comment]
@mbrodala @mcmietz What is the status here? Can it be merged?

**Comment by mcmietz** [comment]
@linawolf I think it's waiting for the pull request in the blog example, I wouldn't merge the change until it's changed there, otherwise the explanation differs from the example code.

**Comment by susannemoog** [comment]
Pull request in blog_example is merged.

**Pull request merged**
