### PR TITLE
add missing required code for overridden validate method to work

### PR DESCRIPTION
**Pull request by benabbottnz**

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
Many thanks for pointing at this issue.

Did you try to add a parent call: `parent::validate($value);` before custom code? This might be a better solution as the parent method already contains some consistent logic.

Still the missing `return` should be added in any case.

**Comment by benabbottnz** [comment]
Do you mean calling `parent::validate($value)` in a different method, like the constructor? The code I've added is inside the `validate` method already, so adding a parent call would cause an infinite loop.

**Comment by benabbottnz** [comment]
The code in this context of the documentation is for validating more than one field, like comparing 'password' with 'confirm_password', so I'm not sure how using the `parent::validate($value)` method would be used in this case.

**Comment by benabbottnz** [comment]
My understanding of this whole validator could be wrong, but here's an example of how I've used it to validate an entire form using a FrontendUser model:

```php
<?php

namespace Ocular\VersionControlled\Domain\Validator;

use Ocular\VersionControlled\Domain\Model\FrontendUser;
use Ocular\VersionControlled\Utility\SuiteCrmApiUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Error\Result;
use TYPO3\CMS\Extbase\Validation\Error;
use TYPO3\CMS\Extbase\Validation\Validator\AbstractValidator;
use TYPO3\CMS\Extbase\Validation\Validator\EmailAddressValidator;
use TYPO3\CMS\Extbase\Validation\Validator\NotEmptyValidator;

class UpdateUserProfileValidator extends AbstractValidator
{
    public function isValid($value)
    {
        // TODO: Implement isValid() method.
    }

    public function validate($frontendUser)
    {
        // Prepare a result
        $this->result = new Result();

        // Should only validate FrontendUser class
        if (!$frontendUser instanceof FrontendUser) {
            $this->addError('The given object is not a FrontendUser', time());
            return $this->result;
        }

        // Validate first name
        if ($frontendUser->_isDirty('firstName')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getFirstName())->hasErrors()) {
                $this->result->forProperty('firstName')->addError(
                    new Error('Required', time())
                );
            }
        }

        // Validate last name
        if ($frontendUser->_isDirty('lastName')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getLastName())->hasErrors()) {
                $this->result->forProperty('lastName')->addError(
                    new Error('Required', time())
                );
            }
        }

        // Validate Email
        if ($frontendUser->_isDirty('email')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getEmail())->hasErrors()) {
                $this->result->forProperty('email')->addError(
                    new Error('Required', time())
                );
            } elseif (GeneralUtility::makeInstance(EmailAddressValidator::class)->validate($frontendUser->getEmail())->hasErrors()) {
                $this->result->forProperty('email')->addError(
                    new Error('Invalid Email address', time())
                );
            } elseif (GeneralUtility::makeInstance(SuiteCrmApiUtility::class)->getContactByEmailAddress($frontendUser->getEmail())->result_count) {
                $this->result->forProperty('email')->addError(
                    new Error('Already in use', time())
                );
            }
        }

        // Validate phone number
        if ($frontendUser->_isDirty('suitecrmPhoneMobile')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmPhoneMobile())->hasErrors()) {
                $this->result->forProperty('suitecrmPhoneMobile')->addError(
                    new Error('Required', time())
                );
            }
        }

        // Validate address
        if ($frontendUser->_isDirty('suitecrmPrimaryAddressStreet')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmPrimaryAddressStreet())->hasErrors()) {
                $this->result->forProperty('suitecrmPrimaryAddressStreet')->addError(
                    new Error('Required', time())
                );
            }
        }

        if ($frontendUser->_isDirty('suitecrmPrimaryAddressCity')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmPrimaryAddressCity())->hasErrors()) {
                $this->result->forProperty('suitecrmPrimaryAddressCity')->addError(
                    new Error('Required', time())
                );
            }
        }

        if ($frontendUser->_isDirty('suitecrmPrimaryAddressPostalcode')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmPrimaryAddressPostalcode())->hasErrors()) {
                $this->result->forProperty('suitecrmPrimaryAddressPostalcode')->addError(
                    new Error('Required', time())
                );
            }
        }

        if ($frontendUser->_isDirty('suitecrmPrimaryAddressCountry')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmPrimaryAddressCountry())->hasErrors()) {
                $this->result->forProperty('suitecrmPrimaryAddressCountry')->addError(
                    new Error('Required', time())
                );
            }
        }

        // Validate birthdate
        if ($frontendUser->_isDirty('suitecrmBirthdate')) {
            if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmBirthdate())->hasErrors()) {
                $this->result->forProperty('suitecrmBirthdate')->addError(
                    new Error('Required', time())
                );
            }

            if (!\DateTime::createFromFormat('Y-m-d', $frontendUser->getSuitecrmBirthdate())) {
                $this->result->forProperty('suitecrmBirthdate')->addError(
                    new Error('Please use yyyy-mm-dd format', time())
                );
            }
        }

        // Validate gender
        if (GeneralUtility::makeInstance(NotEmptyValidator::class)->validate($frontendUser->getSuitecrmGender())->hasErrors()) {
            $this->result->forProperty('suitecrmGender')->addError(
                new Error('Required', time())
            );
        } elseif (!in_array($frontendUser->getSuitecrmGender(), ['male', 'female', 'other'])) {
            $this->result->forProperty('suitecrmGender')->addError(
                new Error('Invalid option', time())
            );
        }

        return $this->result;
    }
}

**Comment by DanielSiepmann** [comment]
Thanks, I got the wrong understanding, should have invested a bit more time.

Thanks for clarifying. This might also be worth a pull request within TYPO3 Core (Extbase). Looks like an ugly implementation that can be improved.

**Pull request merged**
